# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux:
  ros__parameters:
    topics:
      emergency:
        topic: emergency/cmd_vel
        timeout: 0.5
        priority: 110
      teleop:
        topic   : teleop_node/cmd_vel
        timeout : 0.5
        priority: 100
      uron:
        topic   : uron/cmd_vel
        timeout : 0.5
        priority: 50
      nav2:
        topic: cmd_vel
        timeout: 0.5
        priority: 10